USE sensors;

CREATE TABLE IF NOT EXISTS `data` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Sensor Value` VARCHAR(20),
  `ID1` VARCHAR(20),
  `ID2` VARCHAR(20),
  `Timestamp` TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;
